name: Build Check

on:
  pull_request:
    branches: [ dev ]

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{steps.filter.outputs.client}}
      server: ${{steps.filter.outputs.server}}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  client:
    needs: changes
    if : ${{ needs.changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.18.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Run client build
        run: cd client && npm run build --if-present

  server:
    needs: changes
    if : ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.18.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json

      - name: Install Server dependencies
        run: cd server && npm ci

      - name: Run Server build
        run: cd server && npm run build --if-present
